#!/bin/bash
PRIVKEY=/tmp/testkey
TESTKEY=/tmp/testkey-pub
PRIVTEST=$(ssh-keygen -y -e -f "$PRIVKEY" -P "")
PRIVTEST_CODE=$?
PUBTEST=$(ssh-keygen -y -e -f "$TESTKEY" -P "")
PUBTEST_CODE=$?

if test ! -r /tmp/testkey-pub || test ! -r /tmp/testkey || [ "$PRIVTEST_CODE" -ne "0" ] || [ "$PUBTEST_CODE" -ne "0" ]
then
  echo "1"
  exit
fi

chmod 600 "$PRIVKEY"
chmod 600 "$TESTKEY"
diff -q <( "$PRIVTEST" ) <( "$PUBTEST")
STATUS=$?
rm -f "$PRIVKEY"
rm -f "$TESTKEY"
echo "$STATUS"
