#!/usr/bin/env bash
PRIVKEY=$1
TESTKEY=$2

chmod 600 "$PRIVKEY"
chmod 600 "$TESTKEY"

PRIVTEST=$(ssh-keygen -y -e -f "$PRIVKEY" -P "")
PRIVTEST_CODE=$?
PUBTEST=$(ssh-keygen -y -e -f "$TESTKEY" -P "")
PUBTEST_CODE=$?

if test ! -r ${TESTKEY} || test ! -r ${PRIVKEY} || [ "$PRIVTEST_CODE" -ne "0" ] || [ "$PUBTEST_CODE" -ne "0" ]
then
  echo "1"
  exit
fi

diff -q <(ssh-keygen -y -e -f "$PRIVKEY" -P "") <(ssh-keygen -y -e -f "$TESTKEY" -P "")
STATUS=$?
rm -f "$PRIVKEY"
rm -f "$TESTKEY"
echo "$STATUS"
